### PR TITLE
Add managed storage support

### PR DESCRIPTION
**Pull request by piroor**
I'm planning to deploy this add-on to multiple clients in a company with some modified default options. I hope to use the [managed storage system](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed) instead of modifying of default option definitions. This change will help other people who have same demand. Could you merge this change?

### CODE REVIEW

**Comment by Peuj** [comment]
I've quickly read the documentation (I'm on vacation ^^) and if I understood correctly in managed mode the options cannot be changed by the user.
If it's the case I think I should identify that we are in managed mode and grey the option to "inform" the user that he doesn't have control on the options.
Except that no problem with your request and code.

**Comment by piroor** [comment]
Thank you for reviewing! I agree that UI elements for managed options should be grayed out, so I've added some more commits. [The structure of respond data for the message type `getOptions` is changed to include locked state of options.](https://github.com/Peuj/duplicate-tabs-closer/pull/19/commits/d298714b132c1cb9708286a677dcac490a343466#diff-aeadb1658974dec3e9b6166e8a4b1b9eR23) How about this approach?

**Comment by Peuj** [comment]
Perfect! I'll merge and the update this week end.

**Comment by piroor** [comment]
Thank you for merging!

**Comment by Peuj** [comment]
No problem :)

I've added some modifications:

Log warning when Managed storage manifest not found because I don't consider this as an error
https://github.com/Peuj/duplicate-tabs-closer/commit/d477d2462c88431d5ce48185584f196239c05105

I think it's better to get managedOptions first as localOptions will always be set
https://github.com/Peuj/duplicate-tabs-closer/commit/deb15479d235942de8c61c6e7a438b740b478ad7

Let me know if I've missed something.

**Comment by piroor** [comment]
Hmm, the second change looks unsuitable for my case. On such case no one can override user's preference. I think that managed storage should be used same as the `lockPref()` directive in [MCD (AutoConfig)](https://developer.mozilla.org/en-US/docs/Archive/Misc_top_level/MCD,_Mission_Control_Desktop_AKA_AutoConfig). [`lockPref()` always apply given value even if there is any user value](https://searchfox.org/mozilla-central/rev/325c1a707819602feff736f129cb36055ba6d94f/extensions/pref/autoconfig/src/prefcalls.js#67). On enterprise cases config values defined by the system administrator always must be applied for security or other reasons.

**Comment by Peuj** [comment]
Ok I get it, my bad. I've undo the last change.

If no other problem, I'll push the new version tomorrow.

**Comment by piroor** [comment]
Thanks! I have no concern anymore.

**Pull request merged**
